FROM evergreenitco/corp_website_example_nginx:1.0.10

# Copy our code from local development environment

COPY ./forum_web/loaderio-72823547b69d91e916a28f8a8858455c.txt /forum_code/
COPY ./forum_web/confd /etc/confd/

