version: '2'


services:
  db:
    image: evergreenitco/corp_website_example_mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=P@ssw0rd$$
        - MYSQL_DATABASE=web_counter
        - MYSQL_USER=web_counter
        - MYSQL_PASSWORD=P@ssw0rd!
    ports:
        - "3306"
    
  web:
    image: evergreenitco/corp_website_example_nginx
    ports:
        - "80"

  php:
    image: evergreenitco/corp_website_example_php
    environment:
        - MYSQL_DATABASE=web_counter
        - MYSQL_USER=web_counter
        - MYSQL_PASSWORD=P@ssw0rd!
    ports:
        - "9000"


