[template]
prefix = "/counter"
src = "nginx.tmpl"
dest = "/etc/nginx/conf.d/site.conf"
owner = "nginx"
mode = "0644"
keys = [ 
  "/subdomain",
  "/domain",
]
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"
