kind: PersistentVolume
apiVersion: v1
metadata:
  name: forum-db-nfs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/efs/coreos/forum-db-nfs-pv"
